export const ItemList = [
    {
        id: "1",
        format: "",
        name: "Norton Security Deluxe 2016 - 1 year / 3 Devices (Windows, Android, Mac and IOS)",
        size: "S",
        main_color: "Blue",
        image: "",
        nsln: "123456789012",
        available: "2000",
        price: "12345.67",
        bids: "0",
        time_left: ">1m",
        type: "fixedPrice"
    },
    {
        id: "2",
        format: "",
        name: "Norton Security Deluxe 2016 - 1 year / 3 Devices (Windows, Android, Mac and IOS)",
        size: "S",
        main_color: "Blue",
        image: "",
        nsln: "123456789012",
        available: "2000",
        price: "12345.67",
        bids: "0",
        time_left: ">1m",
        type: "fixedPrice"
    },
    {
        id: "3",
        format: "",
        name: "Norton Security Deluxe 2016 - 1 year / 3 Devices (Windows, Android, Mac and IOS)",
        size: "S",
        main_color: "Blue",
        image: "",
        nsln: "123456789012",
        available: "2000",
        price: "12345.67",
        bids: "4",
        time_left: ">1m",
        type: ""
    },
    {
        id: "4",
        format: "",
        name: "Norton Security Deluxe 2016 - 1 year / 3 Devices (Windows, Android, Mac and IOS)",
        size: "S",
        main_color: "Blue",
        image: "",
        nsln: "123456789012",
        available: "2000",
        price: "12345.67",
        bids: "0",
        time_left: ">1m",
        type: ""
    },
    {
        id: "5",
        format: "",
        name: "Norton Security Deluxe 2016 - 1 year / 3 Devices (Windows, Android, Mac and IOS)",
        size: "S",
        main_color: "Blue",
        image: "",
        nsln: "123456789012",
        available: "2000",
        price: "12345.67",
        bids: "2",
        time_left: ">1m",
        type: ""
    },
    {
        id: "6",
        format: "",
        name: "Norton Security Deluxe 2016 - 1 year / 3 Devices (Windows, Android, Mac and IOS)",
        size: "S",
        main_color: "Blue",
        image: "",
        nsln: "123456789012",
        available: "2000",
        price: "12345.67",
        bids: "6",
        time_left: ">1m",
        type: ""
    },
    {
        id: "7",
        format: "",
        name: "Norton Security Deluxe 2016 - 1 year / 3 Devices (Windows, Android, Mac and IOS)",
        size: "S",
        main_color: "Blue",
        image: "",
        nsln: "123456789012",
        available: "2000",
        price: "12345.67",
        bids: "6",
        time_left: ">1m",
        type: ""
    },
    {
        id: "8",
        format: "",
        name: "Norton Security Deluxe 2016 - 1 year / 3 Devices (Windows, Android, Mac and IOS)",
        size: "S",
        main_color: "Blue",
        image: "",
        nsln: "123456789012",
        available: "2000",
        price: "12345.67",
        bids: "4",
        time_left: ">1m",
        type: ""
    },
    {
        id: "9",
        format: "",
        name: "Norton Security Deluxe 2016 - 1 year / 3 Devices (Windows, Android, Mac and IOS)",
        size: "S",
        main_color: "Blue",
        image: "",
        nsln: "123456789012",
        available: "2000",
        price: "12345.67",
        bids: "0",
        time_left: ">1m",
        type: "fixedPrice"
    },
    {
        id: "10",
        format: "",
        name: "Norton Security Deluxe 2016 - 1 year / 3 Devices (Windows, Android, Mac and IOS)",
        size: "S",
        main_color: "Blue",
        image: "",
        nsln: "123456789012",
        available: "2000",
        price: "12345.67",
        bids: "2",
        time_left: ">1m",
        type: "fixedPrice"
    },
    {
        id: "11",
        format: "",
        name: "Norton Security Deluxe 2016 - 1 year / 3 Devices (Windows, Android, Mac and IOS)",
        size: "S",
        main_color: "Blue",
        image: "",
        nsln: "123456789012",
        available: "2000",
        price: "12345.67",
        bids: "6",
        time_left: ">1m",
        type: "classifiedAd"
    },
]