export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";
export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const TEMPORARY_REQUEST_SUCCESS = 'TEMPORARY_REQUEST_SUCCESS';
export const TEMPORARY_REQUEST_FAIL = 'TEMPORARY_REQUEST_FAIL';
export const SET_TEMPORARY_MESSAGE = 'SET_TEMPORARY_MESSAGE';
export const CLEAR_TEMPORARY_MESSAGE = 'CLEAR_TEMPORARY_MESSAGE';
