export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const TEMP_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const TEMP_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const TEMP_PASSWORD_FAIL    = "FORGOT_PASSWORD_FAIL";

// export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
// export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
// export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const ADD_MOBILE_REQUEST = "LOAD_USER_REQUEST";
export const ADD_MOBILE_SUCCESS = "LOAD_USER_SUCCESS";
export const ADD_MOBILE_FAIL    = "LOAD_USER_FAIL";

export const ADD_MOBILE_verify_REQUEST = "LOAD_USER_REQUEST";
export const ADD_MOBILE_verify_SUCCESS = "LOAD_USER_SUCCESS";
export const ADD_MOBILE_verify_FAIL    = "LOAD_USER_FAIL";

export const TXT_PSWD_REQUEST = "LOAD_USER_REQUEST";
export const TXT_PSWD_SUCCESS = "LOAD_USER_SUCCESS";
export const TXT_PSWD_FAIL    = "LOAD_USER_FAIL";

export const EMAIL_PSWD_REQUEST = "LOAD_USER_REQUEST";
export const EMAIL_PSWD_SUCCESS = "LOAD_USER_SUCCESS";
export const EMAIL_PSWD_FAIL    = "LOAD_USER_FAIL";

export const EMAIL_verify_REQUEST = "LOAD_USER_REQUEST";
export const EMAIL_verify_SUCCESS = "LOAD_USER_SUCCESS";
export const EMAIL_verify_FAIL    = "LOAD_USER_FAIL";

export const ADD_ADDRESS_REQUEST = "LOAD_USER_REQUEST";
export const ADD_ADDRESS_SUCCESS = "LOAD_USER_SUCCESS";
export const ADD_ADDRESS_FAIL    = "LOAD_USER_FAIL";

export const CREATE_PSWD_REQUEST = "LOAD_USER_REQUEST";
export const CREATE_PSWD_SUCCESS = "LOAD_USER_SUCCESS";
export const CREATE_PSWD_FAIL    = "LOAD_USER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const VERIFY_EMAIL_URL_REQUEST = "VERIFY_EMAIL_URL_REQUEST";
export const VERIFY_EMAIL_URL_SUCCESS = "VERIFY_EMAIL_URL_SUCCESS";
export const VERIFY_EMAIL_URL_FAIL = "VERIFY_EMAIL_URL_FAIL";
